/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Administrador;
import Modelo.Expediente;
import Modelo.Interesado;
import java.awt.BorderLayout;
import java.awt.event.KeyEvent;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 * Panel para el registro de nuevos expedientes.
 *
 * @author fernando
 */
public class RGSTExpediente extends javax.swing.JPanel {

    String nombre_archivo;

    /**
     * Crea un nuevo panel de registro de expedientes.
     */
    public RGSTExpediente() {
        initComponents();
    }

    private void ShowJPanel(JPanel p) {
        p.setSize(430, 280);
        p.setLocation(0, 0);

        MenuPrincipal.content.removeAll();
        MenuPrincipal.content.add(p, BorderLayout.CENTER);
        MenuPrincipal.content.revalidate();
        MenuPrincipal.content.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbxAsunto = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        bttnRegistrar = new javax.swing.JButton();
        bttnSeleccionar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        bttnVer = new javax.swing.JButton();
        cbxPrioridad = new javax.swing.JComboBox<>();
        cbxEsMiembro = new javax.swing.JCheckBox();

        setPreferredSize(new java.awt.Dimension(410, 280));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(410, 280));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel1.setText("Expediente");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        txtDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDNIActionPerformed(evt);
            }
        });
        txtDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDNIKeyReleased(evt);
            }
        });
        jPanel1.add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 120, -1));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 120, -1));

        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyReleased(evt);
            }
        });
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 120, -1));
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 120, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel2.setText(" DNI");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 20, 20));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel3.setText(" Nombres");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 20));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel4.setText("Documento");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, 20));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel5.setText(" Email");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 83, -1, 20));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel6.setText("Interesado");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel7.setText(" Asunto");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 60, 20));

        cbxAsunto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solicitud psicológica", "Apoyo social", "Registro laboral", "Certificado prácticas", "Cita médica", "Certificado salud" }));
        cbxAsunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxAsuntoActionPerformed(evt);
            }
        });
        jPanel1.add(cbxAsunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 120, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel8.setText(" Prioridad");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 60, 20));

        bttnRegistrar.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        bttnRegistrar.setText("Registrar");
        bttnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(bttnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 130, 80));

        bttnSeleccionar.setText("Adjuntar");
        bttnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnSeleccionarActionPerformed(evt);
            }
        });
        jPanel1.add(bttnSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 130, -1));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel9.setText(" Teléfono");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, 20));

        bttnVer.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        bttnVer.setText("Ver");
        bttnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnVerActionPerformed(evt);
            }
        });
        jPanel1.add(bttnVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 189, 120, 80));

        cbxPrioridad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alta", "Media", "Baja" }));
        jPanel1.add(cbxPrioridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 120, -1));

        cbxEsMiembro.setText("Miembro UL");
        jPanel1.add(cbxEsMiembro, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bttnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnSeleccionarActionPerformed
        JFileChooser j = new JFileChooser();
        FileNameExtensionFilter fi = new FileNameExtensionFilter("pdf", "pdf");
        j.setFileFilter(fi);

        int se = j.showOpenDialog(this);

        if (se == 0) {
            this.bttnSeleccionar.setText("" + j.getSelectedFile().getName());
            nombre_archivo = j.getSelectedFile().getName();
        }
    }//GEN-LAST:event_bttnSeleccionarActionPerformed

    private void bttnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnVerActionPerformed
        // TODO add your handling code here:
        TablaRGSTE t = new TablaRGSTE();
        t.actualizarTabla();
        ShowJPanel(t);
        //System.out.println(nombre_archivo);

    }//GEN-LAST:event_bttnVerActionPerformed

    private void bttnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnRegistrarActionPerformed
        String DNI = txtDNI.getText();
        String Nombres = txtNombre.getText();
        String Telefono = txtTelefono.getText();
        String Email = txtEmail.getText();

        if (!DNI.matches("\\d{8}")) {
            JOptionPane.showMessageDialog(this, "Por favor, el DNI debe tener 8 dígitos.", "DNI inválido", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!Telefono.matches("\\d{9}")) {
            JOptionPane.showMessageDialog(this, "Por favor, el número telefónico debe tener 9 dígitos.", "Teléfono inválido", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String documento = (nombre_archivo != null) ? nombre_archivo : "no aplica";
        String tipo = "Externo";
        
        if (cbxEsMiembro.isSelected()) {
            tipo = "Miembro UL";
        }
        
        
        Interesado i = new Interesado(DNI, Nombres, Telefono, tipo, Email);

        String prioridad = cbxPrioridad.getSelectedItem().toString();
        String asunto = cbxAsunto.getSelectedItem().toString();

        Expediente e = Administrador.crearExpediente(prioridad, i, asunto, documento);

        Administrador.agregar(e);
        Administrador.mostrar();
        Limpiar();
    }//GEN-LAST:event_bttnRegistrarActionPerformed

    //Limpia los campos de los TextFields
    private void Limpiar() {
        this.txtDNI.setText("");
        this.txtEmail.setText("");
        this.txtNombre.setText("");
        this.txtTelefono.setText("");

    }


    private void txtDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDNIActionPerformed
//    RellenarDatos();        // TODO add your handling code here:
    }//GEN-LAST:event_txtDNIActionPerformed

    private void txtDNIKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDNIKeyReleased
        String DNI = txtDNI.getText();
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Expediente exp = Administrador.buscarPorDNI(DNI);
            if (exp != null) {
                Interesado i = exp.getInteresado();
                txtNombre.setText(i.getNombre());
                txtTelefono.setText(i.getTelefono());
                txtEmail.setText(i.getEmail());
            } else {
                Limpiar();
            }
        }
    }//GEN-LAST:event_txtDNIKeyReleased


    private void txtTelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoKeyReleased

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void cbxAsuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxAsuntoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxAsuntoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnRegistrar;
    private javax.swing.JButton bttnSeleccionar;
    private javax.swing.JButton bttnVer;
    private javax.swing.JComboBox<String> cbxAsunto;
    private javax.swing.JCheckBox cbxEsMiembro;
    private javax.swing.JComboBox<String> cbxPrioridad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
