/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Administrador;
import Modelo.Expediente;
import Modelo.Interesado;
import TDA.Cola;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 * Panel para el seguimiento de expedientes, permitiendo derivar, completar y
 * modificar fechas.
 *
 * @author fernando
 */
public class Seguimiento extends javax.swing.JPanel {

    private final DefaultTableModel model;

    /**
     * Crea un nuevo panel de seguimiento.
     */
    public Seguimiento() {
        initComponents();

        String[] columnas = {"ID", "DNI", "Nombre", "Prioridad", "Asunto", "F. Final"};
        model = new DefaultTableModel(columnas, 0);
        TableEXP2.setModel(model);

        mostrarPorPrioridad(false);
    }

    /**
     * Muestra los expedientes en la tabla, ordenados por prioridad y filtrados
     * por estado.
     *
     * @param enProceso Si es verdadero, muestra solo expedientes "En proceso".
     * Si es falso, muestra "Sin derivar".
     */
    public void mostrarPorPrioridad(boolean enProceso) {
        DefaultTableModel modelo = (DefaultTableModel) TableEXP2.getModel();
        modelo.setRowCount(0);

        Cola<Expediente> original = Administrador.ExpedientesPrincipal;
        Cola<Expediente> temp = new Cola<>();
        Cola<Expediente> alta = new Cola<>();
        Cola<Expediente> media = new Cola<>();
        Cola<Expediente> baja = new Cola<>();

        int estadoFiltrar = enProceso ? 2 : 1;

        while (!original.esVacia()) {
            Expediente e = original.desencolar();
            if (e.getEstado() == estadoFiltrar) {
                switch (e.getPrioridad()) {
                    case "Alta":
                        alta.encolar(e);
                        break;
                    case "Media":
                        media.encolar(e);
                        break;
                    case "Baja":
                        baja.encolar(e);
                        break;
                }
            }
            temp.encolar(e);
        }

        while (!temp.esVacia()) {
            original.encolar(temp.desencolar());
        }

        agregarColaATabla(alta, modelo);
        agregarColaATabla(media, modelo);
        agregarColaATabla(baja, modelo);
    }

    private void agregarColaATabla(Cola<Expediente> cola, DefaultTableModel modelo) {
        Cola<Expediente> temp = new Cola<>();
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
        while (!cola.esVacia()) {
            Expediente e = cola.desencolar();
            Interesado i = e.getInteresado();
            String fechaFinal = (e.getFfinal() != null) ? sdf.format(e.getFfinal()) : "N/A";

            modelo.addRow(new Object[]{
                e.getId(),
                i.getDni(),
                i.getNombre(),
                e.getPrioridad(),
                e.getAsunto(),
                fechaFinal
            });
            temp.encolar(e);
        }
        // Restaurar la cola original
        while (!temp.esVacia()) {
            cola.encolar(temp.desencolar());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Filtro = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableEXP2 = new javax.swing.JTable();
        bttnDerivar = new javax.swing.JButton();
        checkEstado = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        bttnCompletar1 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableEXP2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableEXP2.setSurrendersFocusOnKeystroke(true);
        jScrollPane1.setViewportView(TableEXP2);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 410, 190));

        bttnDerivar.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        bttnDerivar.setText("DERIVAR");
        bttnDerivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnDerivarActionPerformed(evt);
            }
        });
        jPanel1.add(bttnDerivar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 140, 60));

        checkEstado.setText("En Proceso");
        checkEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkEstadoActionPerformed(evt);
            }
        });
        jPanel1.add(checkEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setText(" Filtro");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, -1));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 10, 70));

        bttnCompletar1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        bttnCompletar1.setText("COMPLETAR");
        bttnCompletar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCompletar1ActionPerformed(evt);
            }
        });
        jPanel1.add(bttnCompletar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 130, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void checkEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkEstadoActionPerformed
        // TODO add your handling code here:
        mostrarPorPrioridad(checkEstado.isSelected());
    }//GEN-LAST:event_checkEstadoActionPerformed

    private void bttnDerivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnDerivarActionPerformed
        int filaSeleccionada = TableEXP2.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una fila antes de derivar.");
            return;
        }

        String[] opciones = {"Bienestar","Empleabilidad","Dep. Médico"};
        JComboBox<String> comboBox = new JComboBox<>(opciones);

        int opcion = JOptionPane.showConfirmDialog(
                this,
                comboBox,
                "¿A dónde deseas derivar?",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        if (opcion == JOptionPane.OK_OPTION) {
            String dependencia = (String) comboBox.getSelectedItem();
            String dni = (String) TableEXP2.getValueAt(filaSeleccionada, 1);
            Expediente exp = Administrador.buscarPorDNI(dni);
            String actual = exp.getDependencia();
            if (!actual.equalsIgnoreCase("Administrador")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Este expediente ya fue derivado a " + actual + ". No se puede derivar nuevamente.");             
            return;
            }
            Administrador.derivarA(dependencia, exp);
            mostrarPorPrioridad(false);
            JOptionPane.showMessageDialog(this, "Expediente derivado a " + dependencia + ".");
        }

        

    }//GEN-LAST:event_bttnDerivarActionPerformed

    private void bttnCompletar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCompletar1ActionPerformed
        int filaSeleccionada = TableEXP2.getSelectedRow();

        if (filaSeleccionada != -1) {
            int idSeleccionado = (int) TableEXP2.getValueAt(filaSeleccionada, 0);
            String dni=(String) TableEXP2.getValueAt(filaSeleccionada, 1);
            Date fechaActual = new Date();
            if (Administrador.CompletarExpedienteCR(fechaActual, idSeleccionado)) {
                Administrador.agregarFinalizado(Administrador.buscarPorDNI(dni));
                JOptionPane.showMessageDialog(this, "El expediente ha sido completado correctamente (estado: Finalizado).");
            } else {
                JOptionPane.showMessageDialog(this, "Primero debes derivar este expediente antes de completarlo.");
            }

            mostrarPorPrioridad(checkEstado.isSelected());
        } else {
            JOptionPane.showMessageDialog(this, "Selecciona un expediente para completar.");
        }
    }//GEN-LAST:event_bttnCompletar1ActionPerformed

    private void bttnGuardarFechaActionPerformed(java.awt.event.ActionEvent evt) {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Filtro;
    private javax.swing.JTable TableEXP2;
    private javax.swing.JButton bttnCompletar1;
    private javax.swing.JButton bttnDerivar;
    private javax.swing.JCheckBox checkEstado;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
